chore(tests): Print test logs when a variable is unset
This helps debug CI errors like

```
xh: error: error sending request for url (http://localhost:8080/v1/login)

Caused by:
    0: client error (SendRequest)
    1: connection error
    2: Connection reset by peer (os error 104)
/home/runner/work/prose-pod-api/prose-pod-api/tests/integration/run-integration-tests: line 84: ADMIN_TOKEN: parameter null or not set
task: Failed to run task "integration-test": exit status 1
```

diff --git a/tests/integration/run-integration-tests b/tests/integration/run-integration-tests
--- a/tests/integration/run-integration-tests
+++ b/tests/integration/run-integration-tests
@@ -99,6 +99,16 @@ stop() {
 
 source "${INTEGRATION_TESTS_DIR:?}"/util.sh
 
+on_exit() {
+	rc=$?
+	if [ "$rc" -ne 0 ]; then
+		error "Script failed with exit code $rc"
+		print_test_logs
+	fi
+}
+
+trap on_exit EXIT
+
 stepci_run() {
 	local test_file=${1:?}
 	local config_options=${2-test}
