fixup! fix(tests): Make tests more consistent

diff --git a/local-run/scripts/make-demo-scenario b/local-run/scripts/make-demo-scenario
--- a/local-run/scripts/make-demo-scenario
+++ b/local-run/scripts/make-demo-scenario
@@ -102,11 +102,15 @@ start() {
 	# NOTE: We need to run `local` so we can auto-accept invitations.
 	edo FORCE_RUN=1 task local:run -- --api=local --scenario="${SCENARIO_NAME:?}" --detach
 	for _ in $(seq 1 5); do
+		trace 'Waiting a second…'
 		sleep 1
-		xh :8080/v1/version -q && return 0 || :
+		local error="$(edo xh :8080/v1/version -q)" && return 0 || :
 	done
+	error 'API still unreachable after 5s:'
+	error "${error-}"
 	return 1
 }
+info 'Starting the API…'
 start
 
 info 'Create first admin account'
diff --git a/tests/integration/run-integration-tests b/tests/integration/run-integration-tests
--- a/tests/integration/run-integration-tests
+++ b/tests/integration/run-integration-tests
@@ -61,9 +61,12 @@ start() {
 		trace 'Starting the Prose Pod…'
 		task local:run -- --detach --api=local --scenario="${SCENARIO_NAME:?}" --ephemeral
 		for _ in $(seq 1 5); do
+			trace 'Waiting a second…'
 			sleep 1
-			xh :8080/v1/version -q && return 0 || :
+			local error="$(edo xh :8080/v1/version -q)" && return 0 || :
 		done
+		error 'API still unreachable after 5s:'
+		error "${error-}"
 		abort
 	fi
 }
